### PR TITLE
Bump deps, Ember 3.22, yarn upgrade

### PR DESCRIPTION
**Pull request by rwwagner90**
We were seeing some errors in the console from a module not found. Unsure if this fixes it or not, but this should help update a few things, which might help.

### CODE REVIEW

**Comment by rwwagner90** [comment]
It looks like tests aren't running here. Would you be interested in migrating to GitHub actions? I've had to do that for our addons since Travis no longer runs.

**Comment by rwwagner90** [comment]
@paulcwatts any updates here?

**Comment by paulcwatts** [comment]
Oops, sorry I didn't see this before. I'd definitely be interested in moving to GitHub actions.

**Comment by rwwagner90** [comment]
@paulcwatts no worries! I just pushed a change to add GitHub actions, but they won't run until it's merged because my branch is on a fork.

**Pull request merged**
