### PR TITLE
Add `deleteUser` method to `cognito-user` util

### PR DESCRIPTION
**Pull request by mike183**
This PR simply adds the missing `deleteUser` method to the `cognito-user` util.

### CODE REVIEW

**Comment by paulcwatts** [comment]
Thanks for the contribution! Do you mind adding a test? I know it's simple, but like to be thorough. You should be able to base it on one of the simple tests (like the 'resendConfirmationCode' test) in this file: https://github.com/paulcwatts/ember-cognito/blob/master/tests/unit/utils/cognito-user-test.js

**Comment by mike183** [comment]
No worries! Added a test as requested 👍

**Comment by paulcwatts** [comment]
Perfect, thank you for the contribution! 👍

**Comment by paulcwatts** [comment]
Released as 0.9.0. Sorry for the delay!

**Comment by mike183** [comment]
No worries! Thanks for releasing 🎉

**Pull request merged**
